---
node_exporter_version: "1.7.0"
node_exporter_arch: "arm64"  # Change to "armv7" if using 32-bit ARM
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_user: "node_exporter"
