---
kibana_version: "8.x"
kibana_server_host: "0.0.0.0"
kibana_server_port: 5601
elasticsearch_host: "http://localhost:9200"
kibana_user: "kibana"
kibana_group: "kibana"
kibana_install_dir: "/opt/kibana"
kibana_config_dir: "/etc/kibana"
