---
- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    system: yes
    shell: /bin/false
    create_home: no

- name: Create directories for Prometheus
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-arm64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-2.47.2.linux-arm64/prometheus"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Move Prometheus configuration files
  ansible.builtin.copy:
    src: "/tmp/prometheus-2.47.2.linux-arm64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0644'
    remote_src: yes
  loop:
    - prometheus.yml
    - consoles
    - console_libraries

- name: Create systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: Restart Prometheus

- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Add Node Exporter targets to Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Restart Prometheus



